### ISSUE TITLE
Installation through pip fails

### ISSUE THREAD

**Issue by harelba** [dsully/pykafka#2]
Hi,

I'm trying to install pykafka through pip on Ubuntu 11.10 and i'm getting an error trying to find the README.md file.... Performing pip install directly on the git source tree works properly. Seems that the pip "release" is not identical to the current github release.

I'm trying to write a utility which relies on pykafka and this issue makes it harder to use.

Thanks
RL

Full error:

Downloading/unpacking pykafka
  Downloading pykafka-0.1.tar.gz
  Running setup.py egg_info for package pykafka
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/var/tmp/ppp/q/build/pykafka/setup.py", line 12, in <module>
        description = open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/var/tmp/ppp/q/build/pykafka/setup.py", line 12, in <module>

```
description = open('README.md').read(),
```

IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by harelba** [comment]
Another comment on this issue - Using pip install git+https://..... succeeds, but the kafka module is not available from python, so it's not a real success.

RL

**Comment by dsully** [comment]
Should be fixed now.
